const $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>/^https?:\/\//.test(s)?s:'#';
let day='all', plan={}, storageOK=true;
try{plan=JSON.parse(localStorage.getItem('osaka-amazing-5000-2026-v1')||'{}')}catch{storageOK=false}
const byKey=Object.fromEntries(FACILITIES.map(d=>[d.key,d]));
function validPlan(p){let out={};if(!p||typeof p!=='object')return out;for(const [k,v]of Object.entries(p)){if(byKey[k]&&['6','7'].includes(v?.day))out[k]={day:v.day,time:/^\d{2}:\d{2}$/.test(v.time||'')?v.time:'',order:Number(v.order)||0,location:Math.min(Math.max(0,Number(v.location)||0),byKey[k].locations.length-1)}}return out}
plan=validPlan(plan);
const map=L.map('map',{zoomControl:true,scrollWheelZoom:false}).setView([34.676,135.483],12);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,minZoom:10,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>',referrerPolicy:'strict-origin-when-cross-origin',keepBuffer:1}).addTo(map).on('tileerror',()=>{if(!$('.tile-error')){const el=document.createElement('div');el.className='tile-error';el.textContent='地図画像を読めません。ネット接続・ローカル起動を確認してください。';$('#map').append(el)}});
L.control.scale({imperial:false}).addTo(map);
const pins=L.layerGroup().addTo(map),paths=L.layerGroup().addTo(map);let current=[];
for(const k of ['area','category'])for(const v of [...new Set(FACILITIES.map(d=>d[k]))]){const o=document.createElement('option');o.value=v;o.textContent=v;$('#'+k).append(o)}
function blocked(d,dayValue=day){return dayValue==='all'?!!d.closed['6']&&!!d.closed['7']:!!d.closed[dayValue]}
function status(d){return ['6','7'].map(x=>`<span class="${d.closed[x]?'closed':''}">10/${x} ${esc(d.closed[x]||d.statusDefault)}</span>`).join('')}
function addButtons(d){return ['6','7'].map(x=>`<button data-add="${d.key}" data-date="${x}" class="${plan[d.key]?.day===x?'chosen':''}">${plan[d.key]?.day===x?'✓':'＋'} ${x}日</button>`).join('')}
function card(d){return `<article class="card" id="card-${d.key}"><div class="photo" data-detail="${d.key}" tabindex="0" role="button" aria-label="${esc(d.name)}の詳細"><img src="${esc(d.image)}" loading="lazy" alt="${esc(d.name)}"><span class="badge ${d.kind}">${d.kind==='free'?'PASS · 入場対象':'PERK · 特典'} ${d.num}</span></div><div class="card-body"><div class="area">${esc(d.area)} / ${esc(d.category)}</div><h3>${esc(d.name)}</h3><div class="price">${d.kind==='free'?'公式参考料金 '+esc(d.price):esc(d.benefit)}</div><div class="status">${status(d)}</div>${d.warning?`<p class="warning">⚑ ${esc(d.warning)}</p>`:''}<div class="hours">${esc(d.hours)}</div><div class="card-actions"><button class="details" data-detail="${d.key}">詳細・条件</button>${addButtons(d)}</div></div></article>`}
function render(){const q=$('#search').value.toLowerCase();current=FACILITIES.filter(d=>(!$('#kind').value||d.kind===$('#kind').value)&&(!$('#area').value||d.area===$('#area').value)&&(!$('#category').value||d.category===$('#category').value)&&(!$('#hideClosed').checked||!blocked(d))&&(!q||[d.name,d.area,d.category,d.notes,d.benefit,d.warning,d.access].join(' ').toLowerCase().includes(q)));$('#count').textContent=current.length;$('#cards').innerHTML=current.map(card).join('');$('#empty').hidden=!!current.length;$('#picked').textContent=Object.keys(plan).length;renderPins();renderPaths()}
function renderPins(){pins.clearLayers();const groups=[];for(const d of current){for(const loc of d.locations){const entry={...d,name:d.locations.length>1?loc.name:d.name,coords:loc.coords};let g=groups.find(g=>map.distance(g.coords,loc.coords)<23);if(g)g.items.push(entry);else groups.push({coords:loc.coords,items:[entry]})}}for(const g of groups){const d=g.items[0],allBlocked=g.items.every(x=>blocked(x));const icon=L.divIcon({className:'',html:`<div class="pin ${g.items.every(x=>x.kind==='privilege')?'privilege':''} ${allBlocked?'blocked':''}" style="width:32px;height:32px">${g.items.length>1?g.items.length:d.num}</div>`,iconSize:[32,32],iconAnchor:[16,16]});const m=L.marker(g.coords,{icon,title:g.items.map(x=>x.name).join(' / ')}).addTo(pins);m.bindTooltip(`<div class="hover-content"><img src="${d.image}" alt=""><b>${esc(d.name)}</b><small>${esc(d.hours)}</small><p>${esc(d.warning||d.benefit||d.price)}</p><div class="status">${status(d)}</div>${g.items.length>1?`<b>この地点の ${g.items.length} 件</b>${g.items.map(x=>esc(x.name)).join('<br>')}`:''}</div>`,{direction:'auto',opacity:1});const box=document.createElement('div');box.innerHTML=`<b>${esc(d.area)}</b>`;for(const x of g.items){const btn=document.createElement('button');btn.textContent=x.name;btn.onclick=()=>openDetail(x.key);box.append(btn)}m.bindPopup(box)} }
function ordered(x){return Object.keys(plan).filter(k=>plan[k].day===x).sort((a,b)=>plan[a].order-plan[b].order)}
function renderPaths(){paths.clearLayers();for(const x of ['6','7']){const coords=ordered(x).map(k=>byKey[k].locations[plan[k].location||0].coords).filter(Boolean);if(coords.length>1)L.polyline(coords,{color:x==='6'?'#007c76':'#c9703e',weight:3,dashArray:'6 8',opacity:.8}).addTo(paths)}}
function save(){try{localStorage.setItem('osaka-amazing-5000-2026-v1',JSON.stringify(plan))}catch{storageOK=false}render();if($('#planner').open)renderPlan()}
function add(k,x){if(plan[k]?.day===x)delete plan[k];else plan[k]={day:x,time:'',location:0,order:Math.max(0,...Object.values(plan).map(v=>v.order))+1};save();if($('#detail').open)openDetail(k)}
function openDetail(k){const d=byKey[k];$('#detailBody').innerHTML=`<img class="detail-photo" src="${d.image}" alt="${esc(d.name)}"><p class="eyebrow">${esc(d.area)} / ${d.kind==='free'?'FREE':'PERK'} ${d.num}</p><h2>${esc(d.name)}</h2>${window.OSAKA_GUIDE_KEYS?.[k]?`<div class="guide-host" data-guide-id="${window.OSAKA_GUIDE_KEYS[k]}"></div>`:''}<div class="status">${status(d)}</div>${d.warning?`<p class="warning">${esc(d.warning)}</p>`:''}<p>${esc(d.description)}${false?'…':''}</p><dl class="detail-fields"><dt>料金・特典</dt><dd>${esc(d.price)}${d.benefit?'<br>'+esc(d.benefit):''}</dd><dt>営業時間</dt><dd>${esc(d.hours)}</dd><dt>定休日</dt><dd>${esc(d.holiday||'記載なし（営業日要確認）')}</dd><dt>アクセス</dt><dd>${esc(d.access)}</dd></dl><div class="detail-notes"><strong>利用条件・掲載告知</strong><br>${esc([d.notes,d.detailNotes,d.news].filter(Boolean).join('\n\n')||'追加条件の掲載なし。公式で当日の営業を確認してください。')}</div><p class="muted">日付欄は定休日・掲載された告知からの判定です。臨時休業・天候・残席は未確認。写真：公式詳細ページ掲載画像。</p><div class="card-actions">${addButtons(d)}<button data-map="${k}">地図で見る</button></div><div class="detail-links"><a href="${safeUrl(d.url)}" target="_blank" rel="noopener">パス公式の施設詳細 ↗</a>${d.official?`<a href="${esc(safeUrl(d.official))}" target="_blank" rel="noopener">施設公式 ↗</a>`:''}<a href="${esc(d.imageSource)}" target="_blank" rel="noopener">写真の出典 ↗</a>${(d.extraSources||[]).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a>`).join('')}</div>`;if(!$('#detail').open)$('#detail').showModal()}
function warnings(x){const keys=ordered(x),w=[];for(const k of keys){const d=byKey[k];if(d.closed[x])w.push(d.name+'：'+d.closed[x]);if(d.warning)w.push(d.name+'：'+d.warning);if(k==='free-01'&&plan[k].time&&plan[k].time>'15:00')w.push('空中庭園：指定した時刻は15時を過ぎています。無料入場の対象外。')}if(plan['free-01']&&plan['privilege-02'])w.push('空中庭園の入場対象と15時以降の割引を両方選択中。時間と追加料金を確認してください。');const times=keys.filter(k=>plan[k].time);for(let i=1;i<times.length;i++){const minutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));if(minutes(plan[times[i]].time)-minutes(plan[times[i-1]].time)<=0)w.push('入場時刻：'+byKey[times[i-1]].name+' → '+byKey[times[i]].name+' は時刻が同じか、順番が逆です。')}return [...new Set(w)]}
function renderPlan(){$('#planBody').innerHTML=`${!storageOK?'<p class="plan-warning">ブラウザ保存が使えません。JSON保存で選択を残してください。</p>':''}<div class="plan-grid">${['6','7'].map(x=>`<section class="plan-day"><h3>10/${x}（${x==='6'?'火':'水'}） <small>${ordered(x).length}件</small></h3>${ordered(x).length?'':'<p class="muted">施設カードの「＋ '+x+'日」で追加できます。</p>'}${ordered(x).map((k,i)=>`<div class="plan-item"><strong>${i+1}. ${esc(byKey[k].name)}</strong><div class="muted">${esc(byKey[k].area)} / ${esc(byKey[k].hours)}</div>${byKey[k].locations.length>1?`<select data-location="${k}" aria-label="店舗を選ぶ">${byKey[k].locations.map((l,j)=>`<option value="${j}" ${j===(plan[k].location||0)?'selected':''}>${esc(l.name)}</option>`).join('')}</select>`:''}<div><input type="time" value="${esc(plan[k].time)}" data-time="${k}" aria-label="入場時刻"> <button data-up="${k}">↑</button><button data-down="${k}">↓</button><button data-move="${k}">${x==='6'?'7':'6'}日へ</button><button data-remove="${k}">外す</button></div></div>`).join('')}${warnings(x).map(w=>`<p class="plan-warning">⚑ ${esc(w)}</p>`).join('')}</section>`).join('')}</div><p class="legend-path">地図の候補線：6日＝緑 ／ 7日＝オレンジ。滞在時間・交通費・交通経路は合計していません。</p>`}
function reorder(k,delta){const keys=ordered(plan[k].day),i=keys.indexOf(k),j=i+delta;if(j<0||j>=keys.length)return;[keys[i],keys[j]]=[keys[j],keys[i]];keys.forEach((key,index)=>plan[key].order=index+1);save()}
document.addEventListener('click',e=>{const t=e.target.closest('button,[data-detail]');if(!t)return;if(t.dataset.detail)openDetail(t.dataset.detail);if(t.dataset.add)add(t.dataset.add,t.dataset.date);if(t.dataset.map){const d=byKey[t.dataset.map];$('#detail').close();map.setView(d.coords,16);$('#map').scrollIntoView({behavior:'smooth',block:'center'})}if(t.dataset.up)reorder(t.dataset.up,-1);if(t.dataset.down)reorder(t.dataset.down,1);if(t.dataset.remove){delete plan[t.dataset.remove];save()}if(t.dataset.move){const v=plan[t.dataset.move];v.day=v.day==='6'?'7':'6';v.order=Math.max(0,...Object.values(plan).map(x=>x.order))+1;save()}});
document.addEventListener('keydown',e=>{if(e.target.dataset.detail&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openDetail(e.target.dataset.detail)}});
$('#dates').onclick=e=>{if(!e.target.dataset.day)return;day=e.target.dataset.day;$('#dates').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.day===day));render()};for(const id of ['search','kind','area','category','hideClosed'])$('#'+id).addEventListener(id==='search'?'input':'change',render);
$('#fit').onclick=()=>{const coords=current.flatMap(d=>d.locations.map(l=>l.coords));if(coords.length)map.fitBounds(L.latLngBounds(coords),{padding:[35,35],maxZoom:15})};
$('#closeDetail').onclick=()=>$('#detail').close();$('#closePlan').onclick=()=>$('#planner').close();$('#planToggle').onclick=()=>{renderPlan();$('#planner').showModal()};
$('#planBody').addEventListener('change',e=>{if(e.target.dataset.location){plan[e.target.dataset.location].location=Number(e.target.value);save()}if(e.target.dataset.time){plan[e.target.dataset.time].time=e.target.value;save()}});
$('#export').onclick=()=>{const b=new Blob([JSON.stringify({version:1,trip:'amazing-5000-2026-10-06/07',plan},null,2)],{type:'application/json'});const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='osaka-amazing-2days-selection.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('#import').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.trip!=='amazing-5000-2026-10-06/07'||!p.plan)throw Error();plan=validPlan(p.plan);save()}catch{alert('このプランナーから保存したJSONを選んでください。')}e.target.value=''};$('#print').onclick=()=>window.print();render();

const stationsLayer=L.layerGroup();for(const s of STATIONS)L.circleMarker(s.coords,{radius:4,color:'#536d88',weight:1,fillColor:'#fff',fillOpacity:1}).bindTooltip(esc(s.name)+'<br>参考駅位置・対象区間は路線図で確認').addTo(stationsLayer);$('#stationsToggle').onchange=e=>e.target.checked?stationsLayer.addTo(map):map.removeLayer(stationsLayer);$('#transitToggle').onclick=()=>$('#transit').showModal();$('#closeTransit').onclick=()=>$('#transit').close();
