(()=>{
const seenKey='koyasan-opening-seen-v2';
function boot(){
 const body=document.body,controls=document.querySelector('.controls');const locked=()=>window.TripAccess?.locked??false;
 const replay=document.createElement('button');replay.type='button';replay.className='intro-replay';replay.textContent='導入を再生';if(controls)controls.prepend(replay);else{replay.classList.add('standalone-replay');body.append(replay)}
 const overlay=document.createElement('section');overlay.className='koya-intro';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','旅のしおりの導入');
 overlay.innerHTML='<img class="intro-temple" src="assets/koya-intro-mandala.png" alt="" decoding="async"><div class="intro-white"></div><div class="intro-art" role="img" aria-label="白い背景に、墨の円相と中央の梵字・阿"><svg class="intro-enso" viewBox="0 0 1254 1254" aria-hidden="true"><defs><filter id="enso-brush-soft" x="-5%" y="-5%" width="110%" height="110%"><feGaussianBlur stdDeviation="4"/></filter><mask id="enso-brush-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="1254" height="1254"><path id="enso-brush-path" fill="white" filter="url(#enso-brush-soft)"/></mask></defs><image class="intro-enso-image" href="assets/koya-intro-enso-separated.png" width="1254" height="1254" mask="url(#enso-brush-mask)"/></svg><img class="intro-letter" src="assets/koya-intro-a.png" alt="" decoding="async"></div><button type="button" class="intro-skip">スキップ</button><div class="intro-ending"><div class="intro-access"></div><button type="button" class="intro-enter">日程を開く</button></div>';
 body.append(overlay);const bg=overlay.querySelector('.intro-temple'),white=overlay.querySelector('.intro-white'),letter=overlay.querySelector('.intro-letter'),enso=overlay.querySelector('.intro-enso'),ink=overlay.querySelector('.intro-enso-image'),path=overlay.querySelector('#enso-brush-path'),ending=overlay.querySelector('.intro-ending'),skip=overlay.querySelector('.intro-skip'),enter=overlay.querySelector('.intro-enter'),access=overlay.querySelector('.intro-access');
 // Sweep from the lower brush start. A sector avoids exposing the neighboring dry tail early.
 const cx=627,cy=627,r=1000,start=90*Math.PI/180;
 function reveal(progress){const sweep=Math.min(2*Math.PI-.00001,Math.max(.00001,progress*360*Math.PI/180)),sx=cx+r*Math.cos(start),sy=cy+r*Math.sin(start),a=start+sweep,ex=cx+r*Math.cos(a),ey=cy+r*Math.sin(a);path.setAttribute('d',`M ${cx} ${cy} L ${sx} ${sy} A ${r} ${r} 0 ${sweep>Math.PI?1:0} 1 ${ex} ${ey} Z`)}
 ending.inert=true;
 let frame=0,run=0,previousFocus=null,active=false;const clamp=v=>Math.min(1,Math.max(0,v)),smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
 const params=new URLSearchParams(location.search),preview=params.has('intro-preview');const previewFrame=preview&&params.has('intro-frame')?Math.min(8.2,Math.max(0,Number(params.get('intro-frame'))||0)):null;function record(){if(preview)return;try{localStorage.setItem(seenKey,'yes')}catch{}}
 const assets=[bg,letter,new Image()];assets[2].src='assets/koya-intro-enso-separated.png';
 function ready(){return Promise.all(assets.map(img=>img.decode().catch(()=>{})))}
 function finish(){bg.style.opacity='0';white.style.opacity='1';letter.style.opacity='1';letter.style.filter='none';letter.style.transform='translate(-50%,-50%) scale(1)';enso.style.filter='none';ink.removeAttribute('mask');ending.inert=false;ending.classList.add('is-ready');overlay.classList.add('intro-ended');skip.textContent='閉じる';skip.hidden=locked();enter.hidden=locked();access.hidden=!locked();overlay.dataset.stage='complete'}
 async function play(manual=false){const id=++run;cancelAnimationFrame(frame);previousFocus=active?previousFocus:document.activeElement;active=true;overlay.hidden=false;overlay.classList.remove('is-closing','intro-ended');overlay.dataset.stage='loading';ending.classList.remove('is-ready');ending.inert=true;enter.hidden=locked();access.hidden=!locked();if(locked())window.TripAccess.mount(access,close);skip.hidden=false;skip.textContent='スキップ';bg.style.opacity='1';bg.style.transform='scale(1.05)';white.style.opacity='0';letter.style.opacity='0';letter.style.filter='invert(1) blur(14px)';enso.style.filter='invert(1)';ink.setAttribute('mask','url(#enso-brush-mask)');reveal(0);path.style.visibility='hidden';body.classList.add('intro-open');for(const child of body.children)if(child!==overlay)child.inert=true;skip.focus({preventScroll:true});record();await ready();if(id!==run)return;
 // The building motion switch never suppresses the opening sequence.
 const epoch=performance.now();function tick(now){if(id!==run)return;const t=previewFrame===null?(now-epoch)/1000:previewFrame;const appear=smooth((t-.55)/2.1),draw=smooth((t-2.45)/5.05),wash=smooth((t-2.9)/4.5),toInk=smooth((t-3.5)/3.0);overlay.dataset.stage=t<2.45?'arrival':t<7.5?'brush':'settling';bg.style.transform=`scale(${1.05-.025*clamp(t/7)})`;bg.style.opacity=String(1-wash);white.style.opacity=String(wash);letter.style.opacity=String(appear);letter.style.transform=`translate(-50%,-50%) scale(${1.06-.06*appear})`;letter.style.filter=`invert(${1-toInk}) blur(${14*(1-appear)}px)`;enso.style.filter=`invert(${1-toInk})`;path.style.visibility=draw>0?'visible':'hidden';reveal(draw);if(draw>=1)ink.removeAttribute('mask');if(t>=8.2){finish();return}if(previewFrame===null)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)
 }
 function close(){if(locked()){++run;cancelAnimationFrame(frame);finish();return}if(!active)return;active=false;++run;cancelAnimationFrame(frame);overlay.classList.add('is-closing');body.classList.remove('intro-open');for(const child of body.children)if(child!==overlay)child.inert=false;const closeId=run;setTimeout(()=>{if(run===closeId&&!active){overlay.hidden=true;overlay.classList.remove('is-closing')}},matchMedia('(prefers-reduced-motion: reduce)').matches?0:650);previousFocus?.focus?.({preventScroll:true})}
 replay.addEventListener('click',()=>play(true));skip.addEventListener('click',close);enter.addEventListener('click',close);overlay.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const buttons=Array.from(overlay.querySelectorAll('button,input')).filter(el=>!el.hidden&&!el.closest('[hidden]')&&(!el.closest('.intro-ending')||ending.classList.contains('is-ready'))),index=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(index+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus()}});
 let seen=false;try{seen=localStorage.getItem(seenKey)==='yes'}catch{}if(preview||!seen||locked())play(false)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
